/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package android.game;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int Lost=0x7f040005;
        public static final int Pause=0x7f040001;
        public static final int Quit=0x7f040004;
        public static final int QuitG=0x7f040007;
        public static final int Replay=0x7f040006;
        public static final int Restart=0x7f040003;
        public static final int Resume=0x7f040002;
        public static final int app_name=0x7f040000;
    }
}
